### PR TITLE
Add support for the Xiaomi Mija Robot Vacuum 1T (dreame.vacuum.p2041)

### PR DESCRIPTION
**Pull request by thiete**
I just got this robot. The miot command set is almost identical to dreame.vacuum.p2008. Everything seems to work.

I also wanted room cleaning functionality. I have added a room_clean action for the vacuum which calls the cleaning command with the appropriate parameters to initiate targeted cleaning. The custom action definition for room cleaning in the homebridge config has to be something like:

{
    "action": "room_clean",
    "name": "Clean Kitchen",
    "params": [
        18,
        "{\"selects\": [[4,1,1,2,1]]}"
    ]
}

The first parameter of 18 is passed to piid 1 and indicates room cleaning (19 would be area cleaning).
The value in the double square brackets, passed to piid 10,  is then:
[[room_id, number of cleaning repetitions, vacuum power, mopping water flow, index]]
I believe multiple rooms to be cleaned can also be selected. 
I got this command format from the discussion here: https://github.com/rytilahti/python-miio/issues/870#issue-751099906 

In my case the room IDs were simply 1,2,3,4 and I figured out which room they correspond to manually.

### CODE REVIEW

**Comment by merdok** [comment]
Thanks! From what I can see everything looks clean and good! Will merge it later! 
Also thanks for explaining how the room cleaning works, I was wondering that myself how the passed parameters should look like. Thou I think they look different for other devices, anyway I think I will include that info in the README.

**Comment by merdok** [comment]
One more question how do you know that the room clean has two parameters? Since in the spec there is only one parameter described, only 10...

**Comment by thiete** [comment]
need2buy posted a comment [here](https://github.com/rytilahti/python-miio/issues/870#issuecomment-850623325) with some code attached. This included the function room_id_cleanup below:

```
    # @command(click.argument("coords", type=str, ""))
    def room_id_cleanup(self, rooms, repeats,clean_mode,mop_mode) -> None:
        """Start room-id cleaning."""
        # clean_mode = 3
        # mop_mode = 3
        cleanlist = []
        for sublist in rooms:
            if len(sublist) > 1:
                repeats = sublist[1]
            if len(sublist) > 2:
                clean_mode = sublist[2]
            if len(sublist) > 3:
                mop_mode = sublist[3]    
            cleanlist.append([ ord(sublist[0].upper()) - 64, repeats, clean_mode, mop_mode, rooms.index(sublist) + 1 ])
        payload = [{"piid": 1, "value": 18}, {"piid": 10, "value": "{\"selects\": " + str(cleanlist).replace(' ','') + "}"  }]
        return self.call_action(4, 1, payload)
```

I have no idea myself how the guys over at python_miot figured out the command format.

**Comment by merdok** [comment]
Just as a small update, in the upcoming update i removed the ROOM_CLEAN action and instead i have added the room clean parameters to the START_CLEAN action which has the same id. I think there is no need to split it in two actions. You will need to adjust your config then when the update is out!

**Comment by thiete** [comment]
Thanks for cleaning up the specification for the 1T! I see I missed a few differences.
It seems the start clean action is back to how it was without the mysterious 1 parameter, but your comment implies it may be a typo?

> this.addAction(RobotCleanerActions.START_CLEAN, 4, 1, [10]);  // 1 parameter is not in the spec, from where comes the parameters?

I don’t mind just keeping a fork of this with the action added if it’s just a hack for the one device model. It does seem like room cleaning is a desirable feature and it would be nice to see it added in a more general implementation, but it’s always going to be a bit of hassle for the user to figure out the room ids etc. 
I would ultimately want to replicate the behaviour of the homebridge-Xiaomi-roborock-vacuum plug-in where you can select multiple rooms and then then the cleaning gets triggered after a small delay with the selected rooms. Not sure I have the bandwidth to implement it if I’m honest. Quite simple logic, but I would have to implement some stateful “custom actions”.

**Comment by merdok** [comment]
Ahhh, that is my mistake. I do not know how this slipped through. Of course I wanted to add the 1 parameter there but somehow I forgot... Will correct that in the next update!

**Pull request merged**
