### PR TITLE
Support lumi.acpartner.mcn02

### PR DESCRIPTION
**Pull request by jianyun8023**
- #52

### CODE REVIEW

**Comment by merdok** [comment]
Hi, thanks for the PR, but as already mentioned here #52 i will add support for that device. In fact i already have the device implemented locally...

**Comment by jianyun8023** [comment]
@merdok Haha, either way can be used.  I tried how to test the plugin in homebridge yesterday.  By the way, I tried this device.

When I have time in the future, I will do some pr to submit new device support.

**Comment by merdok** [comment]
So the device works as expected with this PR? :) So i at least know if the support is correct.

That would be great, any PR's with new devices support are appreciated and welcome!

**Comment by jianyun8023** [comment]
@merdok Yes, it works, I have used it on homebridge.

**Comment by merdok** [comment]
Version 0.9.7 with the device support just got released!

**Comment by jianyun8023** [comment]
@merdok I encountered an error after updating 0.9.7, please refer to my pr.
`Poll failed! No response from device! TypeError: this.getDevice(...).supportsSwingModes is not a function`.

The other is because there is no current ambient temperature, it is recommended to set the value to target temperature.

**Comment by merdok** [comment]
Oh, sorry for the error! Will fix that in the next update. 

Do you think it is better to set the current temperature to the target temperature in that case then set it to 0 degree? I was wondering how the air conditioner works if it cannot read the current temperature. I mean in that case it has no relation to how much it should heat...

**Comment by jianyun8023** [comment]
@merdok If the current temperature is not set, it will be displayed as 0, I think it will not affect the cooling or heating. I don’t like the display as 0 on the UI.

**Comment by jianyun8023** [comment]
image
image

**Comment by merdok** [comment]
Yeah you are right, it actually makes more sense to display the target temperature in that case instead of 0. Will adjust that in the next update!

**Pull request closed without merging**
